sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build
  - ./gradlew task singleApp:createDockerfile
  - ./gradlew task singleApp:dockerCopyDistResources

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # SINGLE_APP SERVICE
  - export SINGLE_APP=sky233/single-app
  - docker build -t $SINGLE_APP ./singleApp/build/docker
  - docker tag $SINGLE_APP $SINGLE_APP:$TAG
  - docker push $SINGLE_APP

